override:
  ceph:
    log-whitelist:
      - HEALTH_WARN OSD_
      - HEALTH_WARN PG_
      - HEALTH_WARN SMALLER_PGP_NUM
      - HEALTH_WARN DEGRADED_OBJECTS
      - HEALTH_WARN MISPLACED_OBJECTS
      - HEALTH_WARN SLOW_REQUESTS
